# Site settings
title: Bob Gardner
email: bob.hn.gardner@gmail.com
description: >- # ignores newlines until 'baseurl:'
  Bob Gardner's personal website.
baseurl: ""
url: "https://www.bob-gardner.com"
twitter_username: rgardner929
github_username:  rgardner
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - tasks.py
  - README.md
  - script
  - vendor

collections:
  resources:
    output: true
    permalink: /resources/:path/

plugins:
  - jekyll-seo-tag

social:
  name: Bob Gardner
  links:
    - https://github.com/rgardner/
    - https://www.linkedin.com/in/robertgardner1/
    - https://www.facebook.com/BobHGardner
    - https://twitter.com/rgardner929
    - https://keybase.io/rgardner
