# Site settings
title: Robert Gardner
email: robert.gardner@nyu.edu
description: "Thoughts from the intersection of economics and computer science."
baseurl: ""
url: "http://rgardner.github.io/"
twitter_username: rgardner929
github_username:  rgardner

# Build settings
markdown: kramdown
permalink: pretty
