#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --assume-extension --http-status-ignore "999,401,403" ./_site
bundle exec github-pages health-check
