#!/bin/bash

set -euo pipefail

# dancingtoether was decomissioned
# twitter requires custom user agent not available from htmlproofer CLI
URL_IGNORE="/dancingtogether.live/,/twitter.com/,/t.co/"

bundle exec htmlproofer \
  --enforce-https=false \
  --ignore-status-codes 301,401,403,429,999 \
  --ignore-urls "${URL_IGNORE}" \
  --swap-urls "https\:\/\/www.bob-gardner.com:" \
  ./_site
