#!/usr/bin/env bash
# Creates a new draft Jekyll post

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
readonly repo_root

readonly drafts_dir="${repo_root}/_drafts"
mkdir -p "${drafts_dir}"

name="${drafts_dir}/$(date '+%Y-%m-%d')-change-me.md"

cat <<-EOF >"$name"
---
layout: post
title: INSERT TITLE HERE
tags: [INSERT TAGS HERE]
---


EOF
echo "Created new post $name"
