#!/bin/sh
# Create a new Jekyll post

set -euo pipefail

name="_drafts/$(date '+%Y-%m-%d')-change-me.md"

cat <<-EOF >"$name"
---
layout: post
title: INSERT TITLE HERE
tags: [INSERT TAGS HERE]
---


EOF
echo "Created new post $name"
