#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer \
  --assume-extension \
  --http-status-ignore "301,401,403,999" \
  ./_site

bundle exec github-pages health-check
